#!/usr/bin/Rscript
library("fpc")
args <- commandArgs()
#print (args[6])
data<-read.delim(args[6],sep="\t", header = T, row.names=1)
#head(data)
model3 <- dbscan(data, eps=60, MinPts=5)
a1<-cbind(model3$cluster,args[6],data[,1])
#write.csv(a1,file=paste(args[6],"_cluster"))
write.csv(a1,file=args[7])
print (args[6])
